

---
**Estrutura do repositorio:**
Cada parte ten a súa propia rama onde se encontra o código, un Makefile para a súa compilación e unha captura do resultado obtido.
As ramas dispoñibles son:
- [PrimeiraParte](https://github.com/TheLokin/IGM-OpenGL/tree/PrimeiraParte)
- [SegundaParte](https://github.com/TheLokin/IGM-OpenGL/tree/SegundaParte)
- [TerceiraParte](https://github.com/TheLokin/IGM-OpenGL/tree/TerceiraParte)
- [CuartaParte](https://github.com/TheLokin/IGM-OpenGL/tree/CuartaParte)
---

Para a avaliación desta parte da materia tedes estas dúas prácticas,
con distintas opcións/nota en función do tempo que lle
queirades/poidades adicar.

Lembrade que non haberá preguntas no(s) exame(s) final(is). As
prácticas serán recuperables para a segunda oportunidade, de ser
preciso.

* Práctica OpenGL: Iluminación con Phong

  -> Prazo entrega: 23:59h domingo *23 de xaneiro* 2022

  -> Práctica OpenGL para grupos de 1 a 3 estudantes.

  A partir do esqueleto de código do arquivo
  =spinningcube_withlight_SKEL.cpp= que podedes atopar neste repositorio
  (rama /practicaOpenGL/) tedes que implementar unha iluminación
  simple con Phong sobre un cubo 3D en movemento. A implementación ten
  que funcionar para cámara, punto(s) de luz e cubo 3D en posicións
  arbitrarias.

** Primeira parte (ata 4 puntos sobre 10)

   Cunha soa fonte de luz (luz punto) e co cubo cun único material
   homoxéneo (comportamento idéntico fronte á luz en todos os puntos
   da superficie do cubo), trátase de aplicar Phong shading básico.

   Ver ata diapositiva 11 en =igm_render_teoria3.pdf=

** Segunda parte (ata +2 puntos sobre o anterior)

   Engadide un segundo cubo rotando, máis pequeno, (aproveitade a
   estrutura de datos xa existente), e un segundo punto de luz. No
   tiro de cámara téñense que apreciar as dúas luces.

** Terceira parte (ata +2 puntos sobre o anterior)

   Engadide un mapa difuso nas caras do(s) cubo(s) para o cálculo de
   Phong, o que permite ter distintas propiedades de reflexión difusa
   por fragmento.

   Diapositiva 12 en =igm_render_teoria3.pdf=

** Cuarta parte (ata + 2 puntos sobre o anterior)

   Engadide tamén un mapa especular, que permita distintos
   comportamentos da compoñente especular da luz en función do punto
   iluminado do cubo. O mapa especular ten que ser distinto do mapa
   difuso empregado.

   Diapositiva 13 en =igm_render_teoria3.pdf=

   Ver tamén mapeado de texturas a partir de diapositiva 30 en
   =igm_render_lab2.pdf=

** Entregables

   -> URL a repositorio git co código, no que se vexa o progreso nas
   versións do traballo.

   No repositorio ten que haber:
   - Os arquivos co código fonte e un makefile que constrúa o(s) binario(s)
   - Capturas de pantalla nas que se vexan renders da práctica e,
     ademais, a versión de OpenGL na saída estándar.

   Para a evaluación da práctica é posible que se requira unha defensa
   interactiva da mesma con todas as persoas do grupo de prácticas.